
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class Design_Kasir extends javax.swing.JFrame {


    /**
     * Creates new form Design_Kasir
     */
    public Design_Kasir() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Judul = new javax.swing.JLabel();
        pilihansepeda = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        pil1 = new javax.swing.JRadioButton();
        pil3 = new javax.swing.JRadioButton();
        pil2 = new javax.swing.JRadioButton();
        pil4 = new javax.swing.JRadioButton();
        tmpHarga = new javax.swing.JTextField();
        tmpNama = new javax.swing.JTextField();
        tmpJumlah = new javax.swing.JTextField();
        tmpTotal = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        tmpGambar = new java.awt.Panel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Judul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Judul.setForeground(new java.awt.Color(153, 51, 0));
        Judul.setText("Kasir Penjualan Sepeda");

        pilihansepeda.setText("Pilihan Sepeda");

        harga.setText("Harga Satuan");

        nama.setText("Nama Sepeda");

        jumlah.setText("Jumlah Pembelian");

        total.setText("Total Bayar");

        buttonGroup1.add(pil1);
        pil1.setText("Pil 1 BMX 20 ich");
        pil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(pil3);
        pil3.setText("Pil 3 MTB Senator");
        pil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(pil2);
        pil2.setText("Pil 2 Sepeda Lipat");
        pil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(pil4);
        pil4.setText("pil 4 Dahon K3");
        pil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil4ActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tmpGambar.setMaximumSize(new java.awt.Dimension(3000, 3000));

        javax.swing.GroupLayout tmpGambarLayout = new javax.swing.GroupLayout(tmpGambar);
        tmpGambar.setLayout(tmpGambarLayout);
        tmpGambarLayout.setHorizontalGroup(
            tmpGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        tmpGambarLayout.setVerticalGroup(
            tmpGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pilihansepeda)
                        .addComponent(jumlah)
                        .addComponent(nama, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(total, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(harga))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tmpTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHitung)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pil1)
                                    .addComponent(pil3))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pil2)
                                    .addComponent(pil4)))
                            .addComponent(tmpNama, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tmpJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tmpHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(tmpGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(Judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Judul)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilihansepeda)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pil1)
                                .addComponent(pil2)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pil3)
                            .addComponent(pil4))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga)
                            .addComponent(tmpHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama)
                            .addComponent(tmpNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah)
                            .addComponent(tmpJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHitung)
                            .addComponent(btnHapus)))
                    .addComponent(tmpGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmpTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        int a = Integer.parseInt(tmpHarga.getText());
        int b = Integer.parseInt(tmpJumlah.getText());
        int c = a*b;
        tmpTotal.setText("" + c);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void pil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil1ActionPerformed
        String pilihsepeda;
        if (pil1.isSelected())  {
            pilihsepeda = pil1.getText();
            tmpHarga.setText("785000");
            tmpNama.setText("Sepeda BMX 20 inch");
            JLabel label_gambar = new JLabel (new ImageIcon ("src/imagesepeda/BMX20ich.jpg"));

            label_gambar.setBounds(2, 2, 2, 2);
            label_gambar.setSize(200, 200);
            tmpGambar.add(label_gambar);
            tmpGambar.revalidate();
            tmpGambar.repaint();
        }
        else if (pil1.isSelected()){
            pil2.setSelected(false);
            pil3.setSelected(false);
            pil4.setSelected(false);
        }
        else {
            pil2.setSelected(true);
            pil3.setSelected(true);
            pil4.setSelected(true);
        }
    }//GEN-LAST:event_pil1ActionPerformed

    private void pil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil2ActionPerformed
        String pilihsepeda;
        if (pil2.isSelected())  {
            pilihsepeda = pil2.getText();
            tmpHarga.setText("1275000");
            tmpNama.setText("Sepeda Lipat");
            JLabel label_gambar = new JLabel (new ImageIcon ("src/imagesepeda/SepedaLipat.jpg"));

            label_gambar.setBounds(2, 2, 2, 2);
            label_gambar.setSize(200, 200);
            tmpGambar.add(label_gambar);
            tmpGambar.revalidate();
            tmpGambar.repaint();
        }
    }//GEN-LAST:event_pil2ActionPerformed

    private void pil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil3ActionPerformed
        String pilihsepeda;
        if (pil3.isSelected())  {
            pilihsepeda = pil3.getText();
            tmpHarga.setText("880000");
            tmpNama.setText("Sepeda MTB senator");
            JLabel label_gambar = new JLabel (new ImageIcon ("src/imagesepeda/MTBSenator.jpg"));

            label_gambar.setBounds(2, 2, 2, 2);
            label_gambar.setSize(200, 200);
            tmpGambar.add(label_gambar);
            tmpGambar.revalidate();
            tmpGambar.repaint();
        }
    }//GEN-LAST:event_pil3ActionPerformed

    private void pil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil4ActionPerformed
        String pilihsepeda;
        if (pil4.isSelected())  {
            pilihsepeda = pil4.getText();
            tmpHarga.setText("2800000");
            tmpNama.setText("Sepeda Dahon K3");
            JLabel label_gambar = new JLabel (new ImageIcon ("src/imagesepeda/DahonK3.jpg"));

            label_gambar.setBounds(2, 2, 2, 2);
            label_gambar.setSize(200, 200);
            tmpGambar.add(label_gambar);
            tmpGambar.revalidate();
            tmpGambar.repaint();
        }
    }//GEN-LAST:event_pil4ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String pilihsepeda;
        tmpHarga.setText("");
        tmpJumlah.setText("");
        tmpTotal.setText("");
        tmpNama.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Design_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Design_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Design_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Design_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Design_Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel harga;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel nama;
    private javax.swing.JRadioButton pil1;
    private javax.swing.JRadioButton pil2;
    private javax.swing.JRadioButton pil3;
    private javax.swing.JRadioButton pil4;
    private javax.swing.JLabel pilihansepeda;
    private java.awt.Panel tmpGambar;
    private javax.swing.JTextField tmpHarga;
    private javax.swing.JTextField tmpJumlah;
    private javax.swing.JTextField tmpNama;
    private javax.swing.JTextField tmpTotal;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
